server:
  port:9092

spring:
  application:
    name: Billing management customer
  datasource:
    url: "jdbc:postgresql://localhost:5432/bd_invoice"
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        auto_quote_keyword: true
        ddl-auto: create
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: update
        id:
          new_generator_mappings: false
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB